# events/external_sources.py
from datetime import date

def get_external_events(culture=None, location=None, target_date=None):
    """
    Simulated external events from other websites.
    In a real app you would call Eventbrite/Ticketmaster/etc.
    """

    all_external = [
        {
            "title": "Chicago Christkindlmarket",
            "description": "German Christmas market with food, crafts, and cultural performances.",
            "culture": "European / German",
            "location": "Chicago, IL",
            "place": "Daley Plaza",
            "start_date": date(2025, 11, 21),
            "end_date": date(2025, 12, 24),
            "attendees": 1_300_000,
            "external_url": "https://www.christkindlmarket.com/",
        },
        {
            "title": "Zoolights at Lincoln Park Zoo",
            "description": "Holiday light festival featuring art installations and seasonal activities.",
            "culture": "American",
            "location": "Chicago, IL",
            "place": "Lincoln Park Zoo",
            "start_date": date(2025, 11, 29),
            "end_date": date(2026, 1, 5),
            "attendees": 150_000,
            "external_url": "https://www.lpzoo.org/event/zoolights/",
        },
        {
            "title": "Kwanzaa Celebration at DuSable Museum",
            "description": "African American cultural performances and community gathering.",
            "culture": "African American",
            "location": "Chicago, IL",
            "place": "DuSable Black History Museum",
            "start_date": date(2025, 12, 26),
            "end_date": date(2025, 12, 30),
            "attendees": 5_000,
            "external_url": "https://dusablemuseum.org/",
        },
        {
            "title": "Chanukah Family Fest",
            "description": "Live menorah lighting, music, kids crafts, and cultural food.",
            "culture": "Jewish",
            "location": "Chicago, IL",
            "place": "Illinois Holocaust Museum",
            "start_date": date(2025, 12, 18),
            "end_date": date(2025, 12, 18),
            "attendees": 3_000,
            "external_url": "https://www.ilholocaustmuseum.org/",
        },
        {
            "title": "Navy Pier New Year’s Eve Fireworks",
            "description": "Large waterfront fireworks celebration to ring in the new year.",
            "culture": "American",
            "location": "Chicago, IL",
            "place": "Navy Pier",
            "start_date": date(2025, 12, 31),
            "end_date": date(2025, 12, 31),
            "attendees": 200_000,
            "external_url": "https://navypier.org/",
        },
        {
            "title": "Disney on Ice: Frozen & Encanto",
            "description": "Ice skating show featuring Disney characters and Latino cultural music.",
            "culture": "American / Latin American",
            "location": "Chicago, IL",
            "place": "United Center",
            "start_date": date(2025, 12, 20),
            "end_date": date(2025, 12, 22),
            "attendees": 25_000,
            "external_url": "https://www.disneyonice.com/",
        },
        {
            "title": "Christmas Spectacular Starring the Rockettes",
            "description": "World-famous holiday performance with dance and music.",
            "culture": "American",
            "location": "New York, NY",
            "place": "Radio City Music Hall",
            "start_date": date(2025, 11, 14),
            "end_date": date(2026, 1, 5),
            "attendees": 350_000,
            "external_url": "https://www.rockettes.com/",
        },
        {
            "title": "Times Square New Year’s Eve Ball Drop",
            "description": "Iconic global New Year’s Eve countdown celebration.",
            "culture": "Global",
            "location": "Chicago, IL",
            "place": "Central Park Plaza",
            "start_date": date(2025, 11, 25),
            "end_date": date(2025, 11, 25),
            "attendees": 800,
            "external_url": "https://example.com/street-food-fest",
        },
        {
            "title": "Latin Dance Fiesta",
            "description": "Salsa, Bachata and more.",
            "culture": "Latin American",
            "location": "Chicago, IL",
            "place": "Downtown Dance Hall",
            "start_date": date(2025, 11, 19),
            "end_date": date(2025, 11, 19),
            "attendees": 300,
            "external_url": "https://example.com/latin-dance",
        },
        {
            "title": "Brooklyn Kwanzaa Celebration",
            "description": "African dance, drumming, and cultural traditions.",
            "culture": "African American",
            "location": "Brooklyn, NY",
            "place": "Brooklyn Children’s Museum",
            "start_date": date(2025, 12, 26),
            "end_date": date(2025, 12, 30),
            "attendees": 4_000,
            "external_url": "https://www.brooklynkids.org/",
        },
        {
            "title": "Holiday Lantern Festival",
            "description": "Chinese-style lantern displays with food vendors and entertainment.",
            "culture": "Chinese",
            "location": "New York, NY",
            "place": "Staten Island Zoo Grounds",
            "start_date": date(2025, 11, 23),
            "end_date": date(2026, 1, 12),
            "attendees": 120_000,
            "external_url": "https://www.hellolanternfestival.com/",
        },
        {
            "title": "San Francisco Winter Walk",
            "description": "Open-air holiday market with music, art, and cultural showcases.",
            "culture": "American / Global",
            "location": "San Francisco, CA",
            "place": "Union Square",
            "start_date": date(2025, 12, 1),
            "end_date": date(2025, 12, 24),
            "attendees": 80_000,
            "external_url": "https://visitunionsquaresf.com/",
        },
        {
            "title": "Great Dickens Christmas Fair",
            "description": "Immersive Victorian London festival with costumes and performances.",
            "culture": "British / European",
            "location": "San Francisco, CA",
            "place": "Cow Palace",
            "start_date": date(2025, 11, 22),
            "end_date": date(2025, 12, 21),
            "attendees": 200_000,
            "external_url": "https://dickensfair.com/",
        },
        {
            "title": "Chinese New Year Flower Market",
            "description": "Traditional flower fair celebrating Lunar New Year.",
            "culture": "Chinese",
            "location": "San Francisco, CA",
            "place": "Chinatown",
            "start_date": date(2026, 1, 24),
            "end_date": date(2026, 1, 26),
            "attendees": 60_000,
            "external_url": "https://chineseparade.com/",
        },
        {
             "title": "LA County Holiday Celebration",
            "description": "Free multicultural holiday performances.",
            "culture": "Global",
            "location": "Los Angeles, CA",
            "place": "Dorothy Chandler Pavilion",
            "start_date": date(2025, 12, 24),
            "end_date": date(2025, 12, 24),
            "attendees": 50_000,
            "external_url": "https://www.musiccenter.org/",
        },
        {
             "title": "Hollywood Christmas Parade",
            "description": "Annual parade celebrating American holiday traditions.",
            "culture": "American",
            "location": "Los Angeles, CA",
            "place": "Hollywood Boulevard",
            "start_date": date(2025, 12, 1),
            "end_date": date(2025, 12, 1),
            "attendees": 30_000,
            "external_url": "https://thehollywoodchristmasparade.org/",
        },
        {
           "title": "Japanese New Year Oshogatsu Festival",
            "description": "Cultural demonstrations, food, and performances.",
            "culture": "Japanese",
            "location": "Los Angeles, CA",
            "place": "Little Tokyo",
            "start_date": date(2026, 1, 4),
            "end_date": date(2026, 1, 4),
            "attendees": 10_000,
            "external_url": "https://www.japanese-city.com/",
        },
        {
            "title": "Miami Art Basel Week",
            "description": "Huge international art fair with global exhibits.",
            "culture": "Global",
            "location": "Miami, FL",
            "place": "Miami Beach Convention Center",
            "start_date": date(2025, 12, 4),
            "end_date": date(2025, 12, 7),
            "attendees": 70_000,
            "external_url": "https://www.artbasel.com/",
        },
        {
             "title": "Miami Christmas Near the Beach Festival",
            "description": "Caribbean-influenced holiday celebration with music and food.",
            "culture": "Caribbean / American",
            "location": "Miami, FL",
            "place": "ArtsPark at Young Circle",
            "start_date": date(2025, 12, 20),
            "end_date": date(2025, 12, 20),
            "attendees": 150_000,
            "external_url": "https://www.christmasnearthebeach.com/",
        },
        {
            "title": "Calle Ocho Three Kings Parade",
            "description": "Hispanic cultural parade celebrating Día de los Reyes.",
            "culture": "Latin American",
            "location": "Miami, FL",
            "place": "Little Havana",
            "start_date": date(2026, 1, 6),
            "end_date": date(2026, 1, 6),
            "attendees": 25_000,
            "external_url": "https://calleochocarnival.com/",
        },
        {
            "title": "Atlanta Chinese Lantern Festival",
            "description": "Large lantern displays celebrating Chinese culture.",
            "culture": "Chinese",
            "location": "Atlanta, GA",
            "place": "Centennial Olympic Park",
            "start_date": date(2025, 11, 25),
            "end_date": date(2026, 1, 12),
            "attendees": 100_000,
            "external_url": "https://www.gwcca.org/",
        },
        {
            "title": "Atlanta Kwanzaa Celebration",
            "description": "Community events honoring African heritage and unity.",
            "culture": "African American",
            "location": "Atlanta, GA",
            "place": "Apex Museum",
            "start_date": date(2025, 12, 26),
            "end_date": date(2025, 12, 31),
            "attendees": 7_000,
            "external_url": "https://apexmuseum.org/",
        },
        {
            "title": "Dallas Holiday at the Arboretum",
            "description": "European-style Christmas village with lights and music.",
            "culture": "European",
            "location": "Dallas, TX",
            "place": "Dallas Arboretum & Botanical Garden",
            "start_date": date(2025, 11, 26),
            "end_date": date(2025, 12, 31),
            "attendees": 120_000,
            "external_url": "https://www.dallasarboretum.org/",
        },
        {
            "title": "Texas Tulip Festival – Winter Lights",
            "description": "Light displays and cultural holiday activities.",
            "culture": "American",
            "location": "Dallas, TX",
            "place": "Pilot Point Farms",
            "start_date": date(2025, 12, 10),
            "end_date": date(2026, 1, 10),
            "attendees": 50_000,
            "external_url": "https://texas-tulips.com/",
        },
        {
            "title": "Houston Turkey Leg Festival",
            "description": "Cultural food and music festival with Southern and African influences.",
            "culture": "African American / Southern",
            "location": "Houston, TX",
            "place": "NRG Park",
            "start_date": date(2025, 12, 28),
            "end_date": date(2025, 12, 29),
            "attendees": 8_000,
            "external_url": "https://www.turkeylegfestival.com/",
        },
        {
            "title": "Phoenix ZooLights",
            "description": "Holiday light trail with cultural displays.",
            "culture": "American",
            "location": "Phoenix, AZ",
            "place": "Phoenix Zoo",
            "start_date": date(2025, 11, 27),
            "end_date": date(2026, 1, 19),
            "attendees": 110_000,
            "external_url": "https://www.phoenixzoo.org/",
        },
        {
            "title": "Sedona International Film Festival Winter Series",
            "description": "Independent films showcasing global cultures.",
            "culture": "Global",
            "location": "Sedona, AZ",
            "place": "Harkins Theatres Sedona",
            "start_date": date(2026, 1, 9),
            "end_date": date(2026, 1, 19),
            "attendees": 2_000,
            "external_url": "https://sedonafilmfestival.com/",
        },
        {
            "title": "Denver Parade of Lights",
            "description": "Holiday parade with multicultural performers.",
            "culture": "American / Global",
            "location": "Denver, CO",
            "place": "Downtown Denver",
            "start_date": date(2025, 12, 6),
            "end_date": date(2025, 12, 7),
            "attendees": 20_000,
            "external_url": "https://www.denverparadeoflights.com/",
        },
        {
            "title": "Denver Christkindlmarket",
            "description": "German-style Christmas market with music and food.",
            "culture": "European / German",
            "location": "Denver, CO",
            "place": "Civic Center Park",
            "start_date": date(2025, 11, 21),
            "end_date": date(2025, 12, 23),
            "attendees": 90_000,
            "external_url": "https://www.christkindlmarketdenver.com/",
        },
        {
            "title": "Seattle Winterfest",
            "description": "Cultural winter celebration with ice sculptures and performances.",
            "culture": "American / Global",
            "location": "Seattle, WA",
            "place": "Seattle Center",
            "start_date": date(2025, 11, 29),
            "end_date": date(2026, 1, 5),
            "attendees": 40_000,
            "external_url": "https://www.seattlecenter.com/",
        },
        {
            "title": "Portland Holiday Ale Festival",
            "description": "Craft beer festival with holiday traditions.",
            "culture": "American",
            "location": "Portland, OR",
            "place": "Pioneer Courthouse Square",
            "start_date": date(2025, 12, 4),
            "end_date": date(2025, 12, 8),
            "attendees": 6_000,
            "external_url": "https://holidayale.com/",
        },
        {
            "title": "New Orleans Sugar Bowl New Year’s Parade",
            "description": "Parade blending Cajun, Creole, and American traditions.",
            "culture": "Creole / Cajun / American",
            "location": "New Orleans, LA",
            "place": "French Quarter",
            "start_date": date(2025, 12, 31),
            "end_date": date(2025, 12, 31),
            "attendees": 150_000,
            "external_url": "https://allstatesugarbowl.org/",
        }
    ]

    events = all_external

    if culture:
        cl = culture.lower()
        events = [
            e for e in events
            if cl in e["culture"].lower()
        ]

    if location:
        loc = location.lower()
        events = [
            e for e in events
            if loc in e["location"].lower()
        ]

    if target_date:
        events = [
            e for e in events
            if e["start_date"] <= target_date <= e["end_date"]
        ]

    return events
